### ISSUE TITLE
Magic device support

### ISSUE THREAD

**Issue by SteveAyre** [devolo/dlan-openwrt#1]
Are there any plans to add support for the Magic 1 (homeplug) and Magic 2 (g.hn) devices?

**Comment by Molkenbur** [comment]
Hi Steve, 

good to see, that somebody is interested in this ;-).
For clarification: Both devolo Magic devices are based on the g.hn standard. Magic 1 are SISO devices and Magic 2 are MIMO devices. But they are all interoperable.
Our dLAN devices are based on HomePlug; the latest (1200) are HomePlug AV2 devices.
Currently there is no need to support the community with g.hn firmware, because it is located in a separate flash which is indepentend from the OpenWrt firmware.
One more hint: The Magic 2 WiFi is very close to dLAN 1200+ WiFi ac. Magic 1 WiFi is different and support for OpenWrt is not planned yet.

Regards,
Thomas

**Comment by SteveAyre** [comment]
Thanks for the correction.

**Comment by Rjevski** [comment]
@Molkenbur thanks for the info. I have some questions as I'm considering replacing my dLAN 1200 ac WiFi access points with the Magic 2 ones.

You mention that the firmware for the G.hn modem is on a separate flash; does it mean it works independently from the main firmware, or does it still need the firmware to be loaded at boot time like it's currently done with the AC 1200 WiFi (so needs to extract some files from the official firmware and include them in the OpenWrt image)?

Does the G.hn modem need any configuration utilities, or can it all be done in hardware (via a dedicated push button, etc) independently from the main firmware?

The OpenWrt [tech data page](https://openwrt.org/toh/hwdata/devolo/devolo_magic_2_wifi) mentions that it works with the 1200 Wi-Fi ac image; can you confirm? Does the image work out of the box or is some customisation required?

Finally, if you have any details on this, how is the Wi-Fi chip and/or antenna design on the Magic 2 different from the 1200 ac one? Mine currently top out at 180Mbps on the wireless interface (and I can get 300mbps over the power line), would the Wi-Fi speed also potentially increase, or is the wireless part identical to the ac 1200 one? And does the stock firmware support 802.11r and 802.11k? That was my main reason for using OpenWrt on my 1200 ac ones, as otherwise roaming was so slow (I have 4 of them in the house) I would still get "dead" zones where the phones keep trying to use a far away AP instead of roaming, and when they do the data stream drops momentarily so it's not ideal for voice calls.

Thanks!

**Comment by opechunka** [comment]
Hi,
I tried to build openwrt for Magic 2 WiFi MT3081 taking as an example dLAN pro 1200+ WiFi ac. 
But the first problem,  Magic 2 WiFi MT3081  OEM firmware doesn't have any *.NVM and *.pib files. 
Also it doesn't contain any *3081* files. I just found some ethloader.img and firmware.img. 

How to build openWRT for  Magic 2 WiFi taking into account the above?  Please advise.

**Comment by bong1991** [comment]
Hi @opechunka,

The WiFi component in the Magic 2 WiFi 1-1 is identical to that in the dLAN 1200+ WiFi ac. This means you can use the image for the dLAN 1200+ WiFi ac to set up the device as an Access Point, but the PLC interface won't be functional.

devolo Magic WiFi devices include the necessary firmware image and configuration to boot the G.hn chip. Unfortunately, the tools and files required for this process cannot be open-sourced at this time.

Best regards,
Thomas

**Comment by opechunka** [comment]
Hi @bong1991 ,

Thank you for reply. I've managed to run it as WiFi AP. But the problem and goal is PLC. It's a pity that all is closed and the only way is to spent a lot of time on reverse engenering. 

I see that some guys managed to run PLC on Magic 2 WiFi Next. It looks like no other choise but go their way.

https://forum.openwrt.org/t/installing-openwrt-on-devolo-magic-2-wifi-next/129725

Thanks once more for reaction.

**Comment by jschwartzenberg** [comment]
Hi @bong1991

> devolo Magic WiFi devices include the necessary firmware image and configuration to boot the G.hn chip. Unfortunately, the tools and files required for this process cannot be open-sourced at this time.

I managed to get the tools and scripts as provided by Devolo in `delos_magic-2-wifi-next_6.0.1_2023-09-06.bin` to work with the latest OpenWRT.

Using `patchelf` I patched the binaries to use the new loader and library filenames. Furthermore I patched the shell scripts to allow them to work on the regular OpenWRT.

All-together this means I now have a set of ipk files that can be installed on regular OpenWRT to provide G.hn support on the Devolo Magic 2 WiFi next. Would it be possible to work together to get this into an official package feed?

I can probably go through to the same process to get the MIPS version of these packages for the original Devolo Magic 2 WiFi.

**Comment by bong1991** [comment]
Hi @jschwartzenberg 

I will try to see what I can do here. I guess it's mainly a topic of license and so on. However, I cannot make any promises here.

**Comment by jschwartzenberg** [comment]
> Hi @jschwartzenberg
> 
> I will try to see what I can do here. I guess it's mainly a topic of license and so on. However, I cannot make any promises here.

That would be great! Thank you so much! If useful we could have a conference call in which I elaborate more on how I got it running. I see Devolo has the same solution for chatting and calling that I have at work.

**Comment by jschwartzenberg** [comment]
@bong1991 in the meantime I created this PR: https://github.com/openwrt/openwrt/pull/16789

Of course I can understand if that approach seems far from optimal from your end, but it gives me working G.hn on the latest OpenWRT version :)
A more optimal approach would seem great of course!

**Comment by bong1991** [comment]
Hey @jschwartzenberg 
Thanks for the efforts! If you want to, you can drop me a message in the chatting solution you've mentioned ;-)

**Comment by jschwartzenberg** [comment]
Hi all, for anybody interested in this, see: https://codeberg.org/jschwart/devolo-extract-ghn-packages
Everything is working on the Magic 2 WiFi v1 (MIPS) and next (ARM) devices. Many thanks to the people at Devolo, as without their contributions to OpenWrt and helping to get things going this would not likely have succeeded.

If you have any questions or problems, feel free to create an issue in my repository. It would also be great if you could share it when you get it working. I have received some information through the OpenWrt forums that others were able to successfully get G.hn working with mainline OpenWrt.

(Note regarding the newer model: I understand that the Magic 2 WiFi 6 model uses a WiFi chip for which mainline Linux/OpenWrt support would be a significant endeavor. Somebody interested in that would need to start looking at the sources published by Devolo.)
